# $Id: run_merc.sub,v 1.2 2009/02/15 19:51:06 pzimmerman Exp $
universe = standard
executable = /home/pzimmerman/eccbns/kepler/eccentric_orbit_newt 
#notify_user = pjzimmer@syr.edu
#notification = Always
output = eccentric_orbit_newt.$(cluster).$(process).out
error = eccentric_orbit_newt.$(cluster).$(process).err
log = eccentric_orbit_newt.$(cluster).log
arguments = 0.0 7600543.805 0.0 0.000001 0.000001 1 86400 mikkola 
queue
